config/routes.rb
Rails.application.routes.draw do

  resources :addresses, only: [:index, :create, :edit, :update, :destroy] do
	collection {post :import}
	collection {get :getformat}
	collection {get :getmanual}
  end

  resources :addinfos, only: [:edit, :update]do
  end

  root 'top#index'

  devise_for :users

if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

end

app/models/addinfo.rb
class Addinfo < ActiveRecord::Base
  has_many :addresses

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user
  belongs_to :addinfo

def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      address = find_by(id: row["id"]) || new
      # CSVからデータを取得し、設定する
      address.attributes = row.to_hash.slice(*updatable_attributes)
      # 保存する
      address.save!
    end
  end

  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["ipadd", "use", "status", "addinfo_id"]
  end



end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :addresses

end

app/controllers/addinfos_controller.rb
class AddinfosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_addinfo, only: [:edit, :update]


  def edit
  end

  def update
    @addinfo.update(addinfos_params)
    if @addinfo.save
      # 一覧画面へ遷移して"ブログを編集しました！"とメッセージを表示します。
#      redirect_to addresses_path, notice: "アドレス管理簿を更新しました！"
      flash[:info] = "アドレスDBの名称・説明を更新しました"
      redirect_to addresses_path
    else
     # 入力フォームを再描画します。
     render 'edit'
    end
  end


  private
    def addinfos_params
      params.require(:addinfo).permit(:db_name, :db_info)
    end

    def set_addinfo
      @addinfo = Addinfo.find(params[:id])
    end

end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_address, only: [:edit, :update, :destroy]

  def index
	@addresses = Address.all
	@address = Address.find(1)
  end

#CSVインポート
 def import
    Address.import(params[:file])
    flash[:info] = "アドレスデータをCSVから読み込みました"
    redirect_to addresses_path
 end

#インポート用CSVファイルの書き方お作法
 def getmanual
    csv_name = "manual.txt"
    csvpath = Rails.root.join('public',csv_name)
    send_file(csvpath , disposition: "attachment")
 end

#CSVフォーマットファイルのDL
 def getformat
    csv_name = "format.csv"
    csvpath = Rails.root.join('public',csv_name)
    send_file(csvpath , disposition: "attachment")
 end




  def edit
  end

  def update
   if params[:DL_button]
	#IPAddr形式のアドレスデータをstringに変換、置換対象の文字列を指定
        tmpipadd = @address.ipadd
        ipadd = tmpipadd.to_s
        ptn = "xipaddx"

        #テキストテンプレートの読み込み
        if @address.status == 0
	        #現在未利用（利用開始する）場合はtext_tpl1を読み込み
	        texttpl = @address.addinfo.text_tpl1
        else
	        #現在利用中（廃止する）場合はtext_tpl2を読み込み
	        texttpl = @address.addinfo.text_tpl2
        end

        #テキストテンプレートの読み込み、文中の文字列をアドレスに置換
        tplpath = Rails.root.join('public',texttpl)
        tpl = File.open(tplpath,"r")
        buffer =tpl.read
        buffer.gsub!(ptn, ipadd)

        #出力用テキストファイルを作成・書き込み 
	textfile = "config.txt"
        textpath = Rails.root.join('public',textfile)
        tmptext = File.open(textpath,"w")
        tmptext.write(buffer)

	#テキストテンプレート、出力用テキストを閉じる
        tpl.close()
        tmptext.close()

	#出力用テキストの保存ダイアログを表示
	send_file(textpath , disposition: "attachment")
	return
   else
    @address.update(addresses_params)
    @address.user_id = current_user.id
    if @address.save
      flash[:info] = "利用状況を更新しました"
      redirect_to addresses_path
      return
    else
     # 入力フォームを再描画します。
     render 'edit'
     return
    end

   end
  end


def downloadtext
	#IPAddr形式のアドレスデータをstringに変換、置換対象の文字列を指定
        tmpipadd = @address.ipadd
        ipadd = tmpipadd.to_s
        ptn = "xipaddx"

        #テキストテンプレートの読み込み
        if @address.status == 0
	        #廃止する場合はtext_tpl2を読み込み
	        texttpl = @address.addinfo.text_tpl2
        else
	        #利用する場合はtext_tpl1を読み込み
	        texttpl = @address.addinfo.text_tpl1
        end

        #テキストテンプレートの読み込み、文中の文字列をアドレスに置換
        tplpath = Rails.root.join('public',texttpl)
        tpl = File.open(tplpath,"r")
        buffer =tpl.read
        buffer.gsub!(ptn, ipadd)

        #出力用テキストファイルを作成・書き込み 
	textfile = "text.txt"
        textpath = Rails.root.join('public',textfile)
        tmptext = File.open(textpath,"w")
        tmptext.write(buffer)

	#テキストテンプレート、出力用テキストを閉じる
        tpl.close()
        tmptext.close()

	#出力用テキストの保存ダイアログを表示
	send_file(textpath , disposition: "attachment")
end




  private
    def addresses_params
      params.require(:address).permit(:ipadd, :use, :status, :addinfo_id, :user_id)
    end

    def set_address
      @address = Address.find(params[:id])
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  add_flash_types :success, :info, :warning, :danger

  # before_actionで下で定義したメソッドを実行
  before_action :configure_permitted_parameters, if: :devise_controller?

  #変数PERMISSIBLE_ATTRIBUTESに配列[:name]を代入
  PERMISSIBLE_ATTRIBUTES = %i(name)

  protected

    #deviseのストロングパラメーターにカラム追加するメソッドを定義
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: PERMISSIBLE_ATTRIBUTES)
      devise_parameter_sanitizer.permit(:account_update, keys: PERMISSIBLE_ATTRIBUTES)
    end



end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/addinfos_helper.rb
module AddinfosHelper
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/addinfos/_form.html.erb
<%= form_for(@addinfo) do |f| %>
<div class="form-group">
 <label>DB名称</label>
  <%= f.text_field :db_name, class: 'form-control'  %></P>
</div>

<div class="form-group">
  <label>DB説明</label>
  <%= f.text_field :db_info, class: 'form-control'  %></P>
</div>
  <%= f.submit '編集する', class: 'btn btn-success btn-lg' %>
  <%= link_to '戻る', addresses_path, class: 'btn btn-secondary btn-lg'  %>
<% end %>

app/views/addinfos/edit.html.erb
<div class="container">
  <div class="wrapper col-md-10 col-md-offset-1 col-sm-12">
    <h2>アドレスDBの名称と説明を更新する</h2>

     <%= render 'form' %>
 </div>
</div>

app/views/addresses/_form.html.erb
<%= form_for(@address) do |f| %>
<div class="field">
 <label>IPアドレス</label>
 <P><%= @address.ipadd  %></P>

  <% if @address.status == 0 %>
<div class="form-group">
  <label>利用用途</label>
  <%= f.text_field :use, class: 'form-control'  %></P>
</div>
  <%= f.hidden_field :dbtype, value: 1  %>
  <%= f.hidden_field :status, value: 1 %> <br>
  <P><%= f.submit '設定手順書DL', name: "DL_button", class: 'btn btn-info btn-lg' %></P>
  <%= f.submit '利用開始', class: 'btn btn-success btn-lg',  data: { confirm: '設定手順書はDL済みですか？'} %>
  <%= link_to '戻る', addresses_path, class: 'btn btn-secondary btn-lg'  %>

  <% else %>
  <div class="form-group">
   <label>利用用途(廃止時に消去されます)</label></br>
   <%= @address.use  %></P>
  </div>
  <%= f.hidden_field :use, value: "free"  %>
  <%= f.hidden_field :dbtype, value: 1  %>
  <%= f.hidden_field :status, value: 0 %>
  <P><%= f.submit '設定手順書DL', name: "DL_button", class: 'btn btn-info btn-lg' %></P>
  <%= f.submit '廃止する', class: 'btn btn-danger btn-lg', data: { confirm: '設定手順書はDL済みですか？'} %>
  <%= link_to '戻る', addresses_path, class: 'btn btn-secondary btn-lg'  %>

  <% end %>

  <br>
</div>
<% end %>

app/views/addresses/edit.html.erb
<div class="container">
  <div class="wrapper col-md-10 col-md-offset-1 col-sm-12">
    <h2>アドレス利用状況を更新する</h2>

     <%= render 'form' %>
 </div>
</div>

app/views/addresses/index.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

<br/>
<div class="container">
   <div class="row">
  <div class="wrapper col-md-10 icol-md-offset-1 col-sm-12">
<H3><%= @address.addinfo.db_name %></H3>
<P><%= simple_format(@address.addinfo.db_info) %></P>
<div align="right">
<%= link_to '編集', edit_addinfo_path(@address.addinfo_id), class: 'btn btn-link btn-sm' %>
</div>
 </div>
</div>

  <div class="wrapper col-md-10 col-md-offset-1 col-sm-12">
  <table class="table table-hover table-condensed table-bordered">
   <thead class="thead-dark">
    <tr>
      <th>ID</th>
      <th>IPアドレス</th>
      <th>用途</th>
      <th>割当状況</th>
      <th>更新者</th>
      <th>更新日時</th>
      <th>アクション</th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.order('id').each do |address| %>
      <tr>
        <td><%= address.id %></td>
        <td><%= address.ipadd %></td>
        <td><%= address.use %></td>
	<td>
	<% if address.status == 0%>
		未利用
	<% else %>
		利用中
	<% end %>
	</td>
        <td>
	<% if address.user_id.nil? %>
	-	
	<% else %>
	<%= address.user.name %>
	<% end %>
	</td>
	<td><%= address.updated_at.in_time_zone('Tokyo').strftime("%Y-%m-%d %H:%M:%S") %></td>
        <td>
        <% if address.status == 0%>
	<%= link_to '利用開始', edit_address_path(address), class: 'btn btn-success btn-sm'  %>
	<% elsif address.status == 1%>
	<%= link_to '利用停止', edit_address_path(address), class: 'btn btn-danger btn-sm'  %>
	<% else %>
	※Status異常
	<% end %>
	</td>
      </tr>
    <% end %>
  </tbody>
</table>

<H3>データベースを一括更新する</H3>
<P>既存アドレス情報の変更、及び新しいアドレスを追加することが出来ます。<br>
使い方・CSVサンプルは下記リンクから、右クリックで保存して下さい。</P>
<%= link_to "使い方", getmanual_addresses_path, class: "btn btn-mini btn-link" %>
<%= link_to "CSVサンプル", getformat_addresses_path, class: "btn btn-mini btn-link" %>
<%= form_tag import_addresses_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "インポート" %>
<% end %>
</div>


<div id="page-top-btn" class="page-top-btn">
    <p><a class="move-page-top" id="move-page-top">▲</a></p>
</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>アドレス管理DB</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
      <%= link_to "アドレス管理DB", root_path, class: "navbar-brand" %>
          <ul>
        <%# link要素1 %>
            <li class="nav-item">
                <%= link_to "管理画面", addresses_path, class: "nav-link" %>
            </li>


	<% if user_signed_in? %>
        <%# link要素2 %>
            <li class="nav-item">
                <%= link_to "マイページ", edit_user_registration_path, class: "nav-link" %>
            </li>
        <%# link要素3 %>
            <li class="nav-item">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>

	<% else %>
        <%# link要素2 %>
            <li class="nav-item">
                <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
            </li>
        <%# link要素3 %>
            <li class="nav-item">
                <%= link_to "サインアップ", new_user_registration_path, class: "nav-link" %>
            </li>
	<% end %>
          </ul>
      </div>
    </nav>
 </header>

<%= yield %>

</body>
</html>

app/views/top/index.html.erb
<% if notice %>
  <div class="alert alert-info"><%= notice %></div>
<% end %>
<% if alert %>
  <div class="alert alert-warning"><%= alert %></div>
<% end %>
  <section class="main-header">
  </section>

<section class="about">
 <h1>アドレス管理DBとは</h1>
 <p>IPアドレスの利用・廃止をDBで管理するアプリケーションです。</P>
 <P>利用・廃止時に、ルータ設定用のconfigを出力します。 </p>
<%= link_to "アドレスの管理を行う", 'addresses', class: "btn btn-lg btn-primary" %>
</section>